### ISSUE TITLE
Add simple caching behaviour

### ISSUE THREAD

**Issue by queicherius** [queicherius/gw2api-client#11]
Since writing all the bulk ids can be super straining and we usually request the same ids over and over again, just write the requests itself into the cache?

**Comment by rikkuness** [comment]
I feel like you already implemented this now?

**Comment by queicherius** [comment]
Nope, right now it just caches in memory, but not for subsequent reloads. This is mainly just an idea in case #9 ends up not being an option :(

**Comment by rikkuness** [comment]
Oh client side caching, gotcha

**Comment by queicherius** [comment]
Solved via #9
