### ISSUE TITLE
PvP Leaderboards

### ISSUE THREAD

**Issue by darthmaim** [queicherius/gw2api-client#15]
With the current implementation its not possible to get the leaderboards of the old pvp seasons, beacause the leaderboard was not called `ladder`, but `legendary` and `guild` ([ref](https://api.guildwars2.com/v2/pvp/seasons/44B85826-B5ED-4890-8C77-82DDF9F2CF2B/leaderboards)).

The name of future leaderboards might change again, so its  probably a good idea to not hardcode the leaderboard name.

Edit: And another thing I just noticed, you haven't marked the leaderboard endpoint as paginated, but it is (example: [requesting rank 200 (?page=199&page_size=1)](https://api.guildwars2.com/v2/pvp/seasons/A54849B7-7DBD-4958-91EF-72E18CD659BA/leaderboards/ladder/eu?page=199&page_size=1)).

**Comment by queicherius** [comment]
Thank you for catching that, both things fixed in `v5.0.0`.
