### ISSUE TITLE
Add new endpoints 2017-03-01

### ISSUE THREAD

**Issue by darthmaim** [queicherius/gw2api-client#16]
- [x] /v2/races
 - [x] /v2/dungeons
 - [x] /v2/account/dungeons
 - [x] /v2/raids
 - [x] /v2/account/raids
 - [x] /v2/account/home/nodes
 - [x] /v2/account/home/cats
 - [x] /v2/wvw/upgrades

**Comment by queicherius** [comment]
Thanks! :D You wanna have a go at it? Else I'll probably add it either tomorrow or later today.

**Comment by darthmaim** [comment]
If you are too lazy I can do that after I did gw2treasures/gw2api#105 :P

**Comment by queicherius** [comment]
Just let me know if/when you start, so we don't both do it. 👍

**Comment by Archomeda** [comment]
I'm working on implementing a cat command for my Discord bot... so having this would be nice 👍

**Comment by darthmaim** [comment]
I'm not doing this today, but I can do it sometime tomorrow if you don't want to add them until then.

**Comment by queicherius** [comment]
Gonna start working on this now

**Comment by queicherius** [comment]
Published in `5.1.0`. 😄
