### ISSUE TITLE
Hope can have .d.ts make ide support this

### ISSUE THREAD

**Issue by bluelovers** [queicherius/gw2api-client#33]
Hope can have .d.ts make ide support this
or maybe tweak source to typescript

i try make one
https://github.com/bluelovers/gw2api-client/tree/to-typescript/build

**Comment by queicherius** [comment]
I would be fine merging a PR for adding TS definition support if you want to send one. It should **not** change the source into TS, and the type definitions have to be able to be automatically generated or very easily edited.

**Comment by bluelovers** [comment]
without convert source to ts, i think is not easy make a auto generate
if current code is not change too much, the .d.ts is also easy edit but not for auto generate

---
ts is near current source, so will not too hard change to ts

---
if u ok for take .d.ts, u can just copy it to here

**Comment by queicherius** [comment]
Closing this since there was no discussion for a long while.
